FROM lcas.lincoln.ac.uk/lcastor/lcastor_base
RUN apt-get update -y 
RUN pip3 install --no-cache-dir --upgrade jaraco.functools && pip3 install --upgrade typing-extensions
RUN apt-get install -y portaudio19-dev python3-all-dev vim sqlite3 && pip3 install pyaudio 
RUN pip3 install jinja2 \
    chainlit~=0.7.604 \
    openai~=1.3.5 \
    langchain~=0.0.339 \
    ollama==0.3.3 \
    geocoder \
    requests \
    python-dotenv \
    parsimonious \
    SpeechRecognition \
    llama-index \
    llama-index-llms-ollama==0.3.6 \
    llama-index-embeddings-huggingface \
    llama-index-readers-file \
    llama-index-readers-database \
    llama-index-vector-stores-chroma \
    llama-index-readers-docstring-walker \
    markdown \
    lxml \
    pandas \
    chromadb
RUN pip install transformers pysqlite3-binary

ENTRYPOINT ["/bin/bash", "/home/lcastor/ros_ws/src/LCASTOR/lcastor_docker/entrypoint_ollama.sh"]