name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths: ['lcastor_docker/Dockerfile']
  pull_request:
    branches: [ "main" ]
    paths: ['lcastor_docker/Dockerfile']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: What
      run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
    - name: Docker Login LCAS
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      uses: docker/login-action@v2
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: lcas.lincoln.ac.uk
        # Username used to log against the Docker registry
        username: ${{ secrets.LCAS_REGISTRY_PUSHER }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.LCAS_REGISTRY_TOKEN }}
    - name: Get PR labels
      id: pr-labels
      uses: joerick/pr-labels-action@v1.0.8
    - name: Debug echo
      run: echo "steps.pr-labels.outputs.labels is ${{ steps.pr-labels.outputs.labels }} ${{ contains(steps.pr-labels.outputs.labels, ' docker-build ') }}, github.event.label.name is ${{ github.event.label.name }} and github.event_name is ${{ github.event_name }} and env.BRANCH is ${{ env.BRANCH }}"
    - name: Build and push noetic on focal docker-build PR
      if: ${{ contains(steps.pr-labels.outputs.labels, ' docker-build ') && github.event_name == 'pull_request' }}
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./lcastor_docker/Dockerfile
        platforms: linux/amd64
        push: true
        tags: lcas.lincoln.ac.uk/lcastor/lcastor_base:${{ env.BRANCH }}
#         run: docker build --file ./lcastor_docker/Dockerfile --tag lcas.lincoln.ac.uk/lcastor/lcastor_base:latest
        build-args: |
            UID=1001
            GID=1001
    - name: Build and push noetic on focal 
      if: ${{ github.event.label.name != 'docker-build' }}
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./lcastor_docker/Dockerfile
        platforms: linux/amd64
        push: ${{ github.event_name != 'pull_request' }}
        tags: lcas.lincoln.ac.uk/lcastor/lcastor_base:latest
#         run: docker build --file ./lcastor_docker/Dockerfile --tag lcas.lincoln.ac.uk/lcastor/lcastor_base:latest
        build-args: |
            UID=1001
            GID=1001
