Debug: 
  Active: true
  Mode: "Receptionist" # default 'off' 

Configurations:
  # Modes should have either an Active or Inactive list
  # Active actions are the actions that are enabled in the mode
  # Inactive actions are the actions that are disabled in the mode
  # If BOTH are present, ONLY the Active list will be used
  Receptionist: # name of the mode
    Inactive:
      # activateRasa
      # armAction
      # debug_config
      # findClosestPersonToTrack
      # followPerson
      # followPerson_ats
      # gestureDetection
      # getContinueConfirmation
      # getTextInput
      # getYesNoConfirmation
      # goto
      gotoRoom
      # gotoRoom
      # graspObject
      # gripperAction
      # listen
      # lookAtClosestPerson
      # moveGripperTo
      # moveHead
      # moveTorso
      # navigateForward
      # objectDetection
      # peopleDetection
      # personIdentification
      # recog_action
      # saveGuestData
      # setNavigationMode
      # speak
      # test
      # waitOpenDoor
